# Generated by Django 3.2.25 on 2025-11-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField()),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
