# Generated by Django 3.2.25 on 2025-11-06 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCloudSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soundcloud_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('icon', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.IntegerField()),
                ('url', models.URLField(max_length=500)),
                ('stream_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifySong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('added_at', models.DateTimeField()),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('is_added', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='soundcloudsong',
            name='spotify_song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soundcloud_match', to='spotify_app.spotifysong'),
        ),
    ]
