# Generated by Django 3.2.25 on 2025-11-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_auto_20251106_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotifysong',
            options={'ordering': ['-saved_at']},
        ),
        migrations.RenameField(
            model_name='spotifysong',
            old_name='is_added',
            new_name='is_saved',
        ),
        migrations.RemoveField(
            model_name='spotifysong',
            name='added_at',
        ),
        migrations.AddField(
            model_name='spotifysong',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
