# Generated by Django 3.2.25 on 2025-11-06 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0003_auto_20251106_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifysong',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
