# Generated by Django 3.2.25 on 2025-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0004_spotifysong_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifysong',
            name='added_at',
            field=models.DateTimeField(),
        ),
    ]
