# Generated by Django 3.2.25 on 2025-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0005_alter_spotifysong_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundcloudsong',
            name='download_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soundcloudsong',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
