# Generated by Django 3.2.25 on 2025-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0008_playlist_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='order',
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spotifysong',
            name='in_playlist',
            field=models.BooleanField(default=False),
        ),
    ]
