# Generated by Django 3.2.25 on 2025-11-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0009_auto_20251108_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundcloudsong',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soundcloudsong',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='soundcloudsong',
            name='download_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
